steps:
  # Step 1: Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/fraud-api:latest", "."]

  # Step 2: Push the image to Google Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/fraud-api:latest"]

  # Step 3: Deploy the image to Google Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args: 
      - "run"
      - "deploy"
      - "fraud-api"
      - "--image"
      - "gcr.io/$PROJECT_ID/fraud-api:latest"
      - "--platform"
      - "managed"
      - "--region"
      - "us-central1"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"
      - "--timeout=300s"
      - "--update-env-vars"
      - "PORT=8080"

  # Step 4: Run tests after deployment
  - name: "python"
    entrypoint: "python"
    args: ["test_fraud_api.py"]
    env:
      - "API_URL=https://fraud-api-716102832289.us-central1.run.app/predict"

timeout: "900s"
